### ISSUE TITLE
Can't compile under MSVC2017

### ISSUE THREAD

**Issue by ryobg** [imneme/pcg-cpp#31]
Hello,

the keyword `_forceinline` is not recognized by MSVC2017, which I _guess_ is when you disable the Microsoft specific extension to the ISO C++. Have to be replaced with double underscore prefix instead i.e. `__forceinline`. 

https://github.com/imneme/pcg-cpp/blob/0ca2e8ea6ba212bdfbc6219c2313c45917e34b8d/include/pcg_random.hpp#L96

Best regards.

**Comment by ryobg** [comment]
I thought I looked, but just saw that there is similar issue #11 . Feel free to close due to dublication if you so desire.

**Comment by Neumann-A** [comment]
see pull request #25 
if you need a vs2017 working version you can look into my fork.
[PCG Fork](https://github.com/Neumann-A/pcg-cpp/tree/vs_2017fix_and_cmake)

if you use vcpkg you could also use the port file from my vcpkg fork
[vcpkg fork](https://github.com/Neumann-A/vcpkg/tree/pcg-cpp)
(be aware that the histroy of the branch will be rewritten due to updating/rebasing)

**Comment by ryobg** [comment]
Fixed in merge of #25 (Aug 2018)
