### ISSUE TITLE
Restore from state

### ISSUE THREAD

**Issue by tdegeus** [imneme/pcg-cpp#71]
My simulations rely on a great number of random numbers. However, I want to be able uniquely restore a some given point. To this end I think it would be a good idea to store the current `state` (it would not have to run through the entire sequence starting from some seed). However, it seems that the `state` was not made public. I can image that that might have been on purpose. So: Am I overlooking something? If not, would you be open to making a public API to read/restore a `state`?

**Comment by imneme** [comment]
This is what `operator<<` and `operator>>` do for all (standard-compliant) PRNGs.

**Comment by tdegeus** [comment]
Nice! I somehow did not get that. Thanks!

**Comment by tdegeus** [comment]
(Unrelated) Did you consider having a Python wrapper?

**Comment by imneme** [comment]
There is a version of PCG in NumPy. It's not based on this code.  You could also use ffi, swig, PyObjC, etc. to call the C version (and maybe the C++ version, too).

**Comment by tdegeus** [comment]
Well so it is crucial for me to reproduce the exact sequence in my C++ and Python codes. So I worry that a NumPy 'equivalent' might not be reliable enough. So indeed, it would be better to wrap, maybe using `pybind11`

**Comment by o11c** [comment]
@tdegeus I wrote a Python port of *all* of PCG a while back: https://github.com/o11c/pcg-python

Be aware that performance was an explicit non-goal when I wrote that.

For performance you'd probably want to hard-code a specific engine (because ouch, templates suck when the language doesn't support them), and probably use cython or something.
